import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as request from 'supertest';
import { AppModule } from '../app.module';
import { TripService } from './trip.service';
import { ItineraryService } from './itinerary.service';
import { JwtService } from '@nestjs/jwt';
import { TripStatus } from '../schemas/trip.entity';

/**
 * End-to-end tests for trip API endpoints
 */
describe('Trip API (e2e)', () => {
  let app: INestApplication;
  let tripService: TripService;
  let itineraryService: ItineraryService;
  let jwtService: JwtService;
  let authToken: string;

  const mockUser = { id: 1, email: 'test@example.com' };
  const mockTrip = {
    id: 1,
    title: 'E2E Test Trip',
    description: 'Integration test trip',
    destination: 'Barcelona',
    startDate: new Date('2025-09-01'),
    endDate: new Date('2025-09-07'),
    status: TripStatus.PLANNING,
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    user: mockUser,
    itineraries: [],
    tripShares: [],
  };

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(TripService)
      .useValue({
        createTrip: jest.fn().mockResolvedValue(mockTrip),
        findTripsByUser: jest.fn().mockResolvedValue({
          trips: [mockTrip],
          total: 1,
          page: 1,
          limit: 10,
          totalPages: 1,
        }),
        findTripById: jest.fn().mockResolvedValue(mockTrip),
        updateTrip: jest
          .fn()
          .mockResolvedValue({ ...mockTrip, title: 'Updated Trip' }),
        deleteTrip: jest.fn().mockResolvedValue(undefined),
        shareTrip: jest.fn().mockResolvedValue({
          id: 1,
          tripId: 1,
          shareToken: 'share123',
          expiresAt: new Date('2025-12-31'),
          createdAt: new Date(),
        }),
        duplicateTrip: jest.fn().mockResolvedValue({
          ...mockTrip,
          id: 2,
          title: 'E2E Test Trip (Copy)',
        }),
        searchTrips: jest.fn().mockResolvedValue({
          trips: [mockTrip],
          total: 1,
          page: 1,
          limit: 10,
          totalPages: 1,
        }),
        getSharedTrip: jest.fn().mockResolvedValue(mockTrip),
      })
      .overrideProvider(ItineraryService)
      .useValue({
        createItinerary: jest.fn().mockResolvedValue({
          id: 1,
          tripId: 1,
          day: 1,
          activities: [
            {
              time: '09:00',
              title: 'Visit Park Güell',
              description: "Explore Gaudí's colorful park",
              location: 'Park Güell, Barcelona',
              duration: 120,
            },
          ],
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
        updateItinerary: jest.fn().mockResolvedValue({
          id: 1,
          tripId: 1,
          day: 1,
          activities: [
            {
              time: '10:00',
              title: 'Updated Activity',
              description: 'Updated description',
              location: 'Updated location',
              duration: 90,
            },
          ],
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
        deleteItinerary: jest.fn().mockResolvedValue(undefined),
        generateItinerary: jest.fn().mockResolvedValue({
          id: 1,
          tripId: 1,
          day: 1,
          activities: [
            {
              time: '09:00',
              title: 'AI Generated Activity',
              description: 'Generated by AI',
              location: 'Barcelona Center',
              duration: 180,
            },
          ],
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
      })
      .compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    tripService = moduleFixture.get<TripService>(TripService);
    itineraryService = moduleFixture.get<ItineraryService>(ItineraryService);
    jwtService = moduleFixture.get<JwtService>(JwtService);

    // Generate auth token for testing
    authToken = jwtService.sign({ sub: mockUser.id, email: mockUser.email });
  });

  afterAll(async () => {
    await app.close();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('POST /trips', () => {
    it('should create a new trip', async () => {
      const inputCreateTripDto = {
        title: 'E2E Test Trip',
        description: 'Integration test trip',
        destination: 'Barcelona',
        startDate: '2025-09-01',
        endDate: '2025-09-07',
      };

      const response = await request(app.getHttpServer())
        .post('/trips')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputCreateTripDto)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip created successfully');
      expect(response.body.data.title).toBe(inputCreateTripDto.title);
      expect(tripService.createTrip).toHaveBeenCalledWith(
        expect.objectContaining(inputCreateTripDto),
        mockUser.id,
      );
    });

    it('should return 401 without authentication', async () => {
      const inputCreateTripDto = {
        title: 'Test Trip',
        description: 'Test Description',
        destination: 'Paris',
        startDate: '2025-07-01',
        endDate: '2025-07-07',
      };

      await request(app.getHttpServer())
        .post('/trips')
        .send(inputCreateTripDto)
        .expect(401);
    });

    it('should return 400 with invalid data', async () => {
      const inputInvalidDto = {
        title: '', // Empty title should fail validation
        destination: 'Paris',
        // Missing required fields
      };

      await request(app.getHttpServer())
        .post('/trips')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputInvalidDto)
        .expect(400);
    });
  });

  describe('GET /trips', () => {
    it('should return user trips with pagination', async () => {
      const response = await request(app.getHttpServer())
        .get('/trips?page=1&limit=10')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trips retrieved successfully');
      expect(response.body.data.trips).toHaveLength(1);
      expect(response.body.data.total).toBe(1);
      expect(tripService.findUserTrips).toHaveBeenCalledWith(
        mockUser.id,
        expect.any(Object),
      );
    });

    it('should return 401 without authentication', async () => {
      await request(app.getHttpServer()).get('/trips').expect(401);
    });
  });

  describe('GET /trips/:id', () => {
    it('should return a specific trip', async () => {
      const response = await request(app.getHttpServer())
        .get('/trips/1')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip retrieved successfully');
      expect(response.body.data.id).toBe(mockTrip.id);
      expect(tripService.findTripById).toHaveBeenCalledWith('1', mockUser.id);
    });

    it('should return 400 for invalid trip id', async () => {
      await request(app.getHttpServer())
        .get('/trips/invalid')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(400);
    });
  });

  describe('PUT /trips/:id', () => {
    it('should update a trip', async () => {
      const inputUpdateDto = {
        title: 'Updated Trip',
        description: 'Updated description',
      };

      const response = await request(app.getHttpServer())
        .put('/trips/1')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputUpdateDto)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip updated successfully');
      expect(tripService.updateTrip).toHaveBeenCalledWith(
        '1',
        mockUser.id,
        inputUpdateDto,
      );
    });
  });

  describe('DELETE /trips/:id', () => {
    it('should delete a trip', async () => {
      const response = await request(app.getHttpServer())
        .delete('/trips/1')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip deleted successfully');
      expect(tripService.deleteTrip).toHaveBeenCalledWith(1, mockUser.id);
    });
  });

  describe('POST /trips/:id/share', () => {
    it('should share a trip', async () => {
      const inputShareDto = {
        shareToken: 'share123',
        expiresAt: '2025-12-31T23:59:59.000Z',
      };

      const response = await request(app.getHttpServer())
        .post('/trips/1/share')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputShareDto)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip shared successfully');
      expect(tripService.generateShareLink).toHaveBeenCalledWith(
        '1',
        expect.any(Object),
        mockUser.id,
      );
    });
  });

  describe('POST /trips/:id/duplicate', () => {
    it('should duplicate a trip', async () => {
      const response = await request(app.getHttpServer())
        .post('/trips/1/duplicate')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trip duplicated successfully');
      expect(tripService.duplicateTrip).toHaveBeenCalledWith(1, mockUser.id);
    });
  });

  describe('GET /trips/search', () => {
    it('should search trips', async () => {
      const response = await request(app.getHttpServer())
        .get('/trips/search?keyword=Barcelona&destination=Barcelona')
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Trips found successfully');
      expect(tripService.searchTripsByQuery).toHaveBeenCalledWith(
        mockUser.id,
        expect.any(Object),
      );
    });
  });

  describe('POST /trips/:id/itineraries', () => {
    it('should create an itinerary', async () => {
      const inputCreateItineraryDto = {
        day: 1,
        activities: [
          {
            time: '09:00',
            title: 'Visit Park Güell',
            description: "Explore Gaudí's colorful park",
            location: 'Park Güell, Barcelona',
            duration: 120,
          },
        ],
      };

      const response = await request(app.getHttpServer())
        .post('/trips/1/itineraries')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputCreateItineraryDto)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Itinerary created successfully');
      expect(itineraryService.generateItinerary).toHaveBeenCalledWith(
        '1',
        mockUser.id,
        inputCreateItineraryDto,
      );
    });
  });

  describe('PUT /trips/:id/itineraries/:itineraryId', () => {
    it('should update an itinerary', async () => {
      const inputUpdateItineraryDto = {
        activities: [
          {
            time: '10:00',
            title: 'Updated Activity',
            description: 'Updated description',
            location: 'Updated location',
            duration: 90,
          },
        ],
      };

      const response = await request(app.getHttpServer())
        .put('/trips/1/itineraries/1')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputUpdateItineraryDto)
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Itinerary updated successfully');
      expect(itineraryService.updateDayItinerary).toHaveBeenCalledWith(
        '1',
        mockUser.id,
        1,
        inputUpdateItineraryDto,
      );
    });
  });

  // NOTE: DELETE /trips/:id/itineraries/:itineraryId endpoint is not implemented
  // as deleteItinerary method does not exist in ItineraryService

  describe('POST /trips/:id/generate-itinerary', () => {
    it('should generate an itinerary with AI', async () => {
      const inputGenerateDto = {
        preferences: 'Cultural sites and museums',
        budget: 'moderate',
      };

      const response = await request(app.getHttpServer())
        .post('/trips/1/generate-itinerary')
        .set('Authorization', `Bearer ${authToken}`)
        .send(inputGenerateDto)
        .expect(201);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Itinerary generated successfully');
      expect(itineraryService.generateItinerary).toHaveBeenCalledWith(
        1,
        inputGenerateDto,
        mockUser.id,
      );
    });
  });

  describe('GET /shared/:shareToken', () => {
    it('should return a shared trip without authentication', async () => {
      const response = await request(app.getHttpServer())
        .get('/shared/share123')
        .expect(200);

      expect(response.body.success).toBe(true);
      expect(response.body.message).toBe('Shared trip retrieved successfully');
      expect(tripService.findSharedTripByToken).toHaveBeenCalledWith(
        'share123',
      );
    });
  });
});
